<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5258" started-at="2022-07-07T03:32:31 EDT" finished-at="2022-07-07T03:32:37 EDT">
    <groups>
      <group name="functionalTest">
        <method signature="WebDriver_manager.test04()[pri:0, instance:hw_17.WebDriver_manager@43a0cee9]" name="test04" class="hw_17.WebDriver_manager"/>
      </group> <!-- functionalTest -->
    </groups>
    <test name="Default test" duration-ms="5258" started-at="2022-07-07T03:32:31 EDT" finished-at="2022-07-07T03:32:37 EDT">
      <class name="hw_17.WebDriver_manager">
        <test-method status="PASS" signature="set()[pri:0, instance:hw_17.WebDriver_manager@43a0cee9]" name="set" is-config="true" duration-ms="4582" started-at="2022-07-07T03:32:31 EDT" finished-at="2022-07-07T03:32:36 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set -->
        <test-method status="PASS" signature="test03()[pri:0, instance:hw_17.WebDriver_manager@43a0cee9]" name="test03" duration-ms="3" started-at="2022-07-07T03:32:36 EDT" finished-at="2022-07-07T03:32:36 EDT">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at hw_17.WebDriver_manager.test03(WebDriver_manager.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test03 -->
        <test-method status="PASS" signature="test04()[pri:0, instance:hw_17.WebDriver_manager@43a0cee9]" name="test04" duration-ms="5" started-at="2022-07-07T03:32:36 EDT" finished-at="2022-07-07T03:32:36 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test04 -->
        <test-method status="PASS" signature="test01()[pri:1, instance:hw_17.WebDriver_manager@43a0cee9]" name="test01" duration-ms="31" started-at="2022-07-07T03:32:36 EDT" finished-at="2022-07-07T03:32:36 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test01 -->
        <test-method status="PASS" signature="test02()[pri:0, instance:hw_17.WebDriver_manager@43a0cee9]" name="test02" duration-ms="15" started-at="2022-07-07T03:32:36 EDT" depends-on-methods="hw_17.WebDriver_manager.test01" finished-at="2022-07-07T03:32:36 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test02 -->
        <test-method status="FAIL" signature="test05()[pri:1, instance:hw_17.WebDriver_manager@43a0cee9]" name="test05" duration-ms="16" started-at="2022-07-07T03:32:36 EDT" finished-at="2022-07-07T03:32:36 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Home Page Title doesn't match ... expected [https://www3.mtb.com/personal] but found [M&T Bank - Personal & Business Banking, Mortgages, & More | M&T Bank]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Home Page Title doesn't match ... expected [https://www3.mtb.com/personal] but found [M&T Bank - Personal & Business Banking, Mortgages, & More | M&T Bank]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at hw_17.WebDriver_manager.test05(WebDriver_manager.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test05 -->
        <test-method status="FAIL" signature="test05()[pri:1, instance:hw_17.WebDriver_manager@43a0cee9]" name="test05" duration-ms="4" started-at="2022-07-07T03:32:36 EDT" finished-at="2022-07-07T03:32:36 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Home Page Title doesn't match ... expected [https://www3.mtb.com/personal] but found [M&T Bank - Personal & Business Banking, Mortgages, & More | M&T Bank]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Home Page Title doesn't match ... expected [https://www3.mtb.com/personal] but found [M&T Bank - Personal & Business Banking, Mortgages, & More | M&T Bank]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at hw_17.WebDriver_manager.test05(WebDriver_manager.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test05 -->
        <test-method status="PASS" signature="after()[pri:0, instance:hw_17.WebDriver_manager@43a0cee9]" name="after" is-config="true" duration-ms="577" started-at="2022-07-07T03:32:36 EDT" finished-at="2022-07-07T03:32:37 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after -->
      </class> <!-- hw_17.WebDriver_manager -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
